# Generated by Django 2.1 on 2019-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('Homepage', 'Homepage'), ('For Sale', 'For Sale'), ('Portfolio', 'Portfolio'), ('Home and Sale', 'Home and Sale'), ('Home and Portfolio', 'Home and Portfolio'), ('Sale and Portfolio', 'Sale and Portfolio')], default='Portfolio', max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pubDate', models.DateField()),
            ],
        ),
    ]
